# This workflow will build the static files
# and upload them to the given s3 bucket
name: Deploy to prod

on:
  push:
    branches: ["release"]
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: "https://auth.avantifellows.org"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    
    - name: Install
      run: npm install
    
    # build the vuepress docs
    - name: Build
      env:
        NODE_ENV: Production
        VUE_APP_AF_API_KEY: ${{ secrets.VUE_APP_AF_API_KEY }}
        VUE_APP_BASE_URL_PLIO: ${{ secrets.VUE_APP_BASE_URL_PLIO }}
        VUE_APP_AWS_ACCESS_KEY_ID: ${{ secrets.VUE_APP_AWS_SQS_ACCESS_KEY }}
        VUE_APP_AWS_SECRET_KEY: ${{ secrets.VUE_APP_AWS_SQS_SECRET_ACCESS_KEY }}
        VUE_APP_BASE_URL_MEET: ${{ secrets.VUE_APP_BASE_URL_MEET }}
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # sync with the given S3 bucket
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist s3://af-auth-layer --delete --acl public-read
