name: E2E
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  chrome-desktop:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/e2e/end-to-end.cy.js

  chrome-mobile:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          config: "viewportWidth=375,viewportHeight=667"
          spec: cypress/e2e/end-to-end.cy.js
