name: E2E
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  chrome:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/e2e/end-to-end.cy.js

  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required dependencies
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          spec: cypress/e2e/end-to-end.cy.js
